services:
  operations-api:
    container_name: pfp-operations-api
    # todo: check restart strategies to use the most appropriate one
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://operations-api-database:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - operations-api-database

operations-api-database:
    image: postgres:16.1
    container_name: operations-api-database
    # todo: check restart strategies to use the most appropriate one
    restart: always
    environment:
      POSTGRES_DB: pfp-operations-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      # persist data
      - ./database/data:/var/lib/postgresql/data
      # initialization scripts
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    # TODO: check restart strategies to use the most appropriate one.
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.es
      PGADMIN_DEFAULT_PASSWORD: postgres
